version: "2.4"

services:
  west:
    image: ipsec-alpine:latest
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - ./config/west:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro
    networks:
      secnet:
        ipv4_address: 10.10.0.100

  east:
    image: ipsec-alpine:latest
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - ./config/east:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro
    networks:
      secnet:
        ipv4_address: 10.10.0.200

networks:
  secnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1
